# Generated by Django 3.0.4 on 2020-03-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200322_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (['-published_date'],)},
        ),
    ]
